#!/bin/bash

set -e

if [ "$#" == 0 ]; then
    __sync=true
    __build=true
    __update=true
else
    while test $# -gt 0
    do
        case "$1" in
            sync) __sync=true;;
            build) __build=true;;
            update) __update=true;;
        esac
        shift
    done
fi

root=$(cd $(dirname ${0})/../..; pwd)
build=${root}/build
tools=${root}/tools
third_party=${root}/third_party

python="python"
pip="pip"

identifier=keras

if [ ${__sync} ]; then
    repository=https://github.com/keras-team/${identifier}.git
    mkdir -p ${third_party}
    if [ -d "${third_party}/${identifier}" ]; then
        git -C "${third_party}/${identifier}" fetch -p
        git -C "${third_party}/${identifier}" reset --hard origin/master
    else
        echo "Clone ${repository}..."
        git -C "${third_party}" clone --recursive ${repository}
    fi
fi

echo "Install Keras"
virtualenv=${build}/virtualenv/${identifier}
if [ ${__build} ]; then
    virtualenv -p ${python} ${virtualenv}
fi
if [ -f ${virtualenv}/bin/activate ]; then
    source ${virtualenv}/bin/activate
fi
if [ ${__build} ]; then
    ${pip} install --quiet tensorflow
    ${pip} install ${third_party}/${identifier}
fi

if [ ${__update} ]; then
    echo "Update 'keras-metadata.json'"
    pushd ${tools}/metadata > /dev/null
    ${python} keras-metadata.py
    popd > /dev/null
fi

if [ -f ${virtualenv}/bin/activate ]; then
    deactivate
fi
