#!/bin/bash

set -e

root=$(cd $(dirname ${0})/../..; pwd)
build=${root}/build
tools=${root}/tools
third_party=${root}/third_party

python="python"
pip="pip"

identifier=keras
repository=https://github.com/keras-team/${identifier}.git

mkdir -p ${third_party}

if [ -d "${third_party}/${identifier}" ]; then
    git -C "${third_party}/${identifier}" fetch -p
    git -C "${third_party}/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "${third_party}" clone --recursive ${repository}
fi

echo "Install Keras"
virtualenv=${build}/virtualenv/${identifier}
virtualenv -p ${python} ${virtualenv}
source ${virtualenv}/bin/activate
${pip} install --quiet tensorflow
${pip} install ${third_party}/${identifier}

echo "Update 'keras-metadata.json'"
pushd ${tools}/metadata > /dev/null
${python} keras-metadata.py
popd > /dev/null

deactivate