#!/bin/bash

set -e

if [ "$#" == 0 ]; then
    __sync=true
    __build=true
    __update=true
else
    while test $# -gt 0
    do
        case "$1" in
            sync) __sync=true;;
            build) __build=true;;
            update) __update=true;;
        esac
        shift
    done
fi

root=$(cd $(dirname ${0})/../..; pwd)
build=${root}/build
tools=${root}/tools
third_party=${root}/third_party

python=${python:-python}
pip=${pip:-pip}

if [ ${__sync} ]; then
    repository=https://github.com/scikit-learn/scikit-learn.git
    mkdir -p ${third_party}
    if [ -d "${third_party}/scikit-learn" ]; then
        git -C "${third_party}/scikit-learn" fetch -p
        git -C "${third_party}/scikit-learn" reset --hard origin/master
    else
        echo "Clone ${repository}..."
        git -C "${third_party}" clone --recursive ${repository}
    fi
    if [ -d "${third_party}/lightgbm" ]; then
        git -C "${third_party}/lightgbm" fetch -p
        git -C "${third_party}/lightgbm" reset --hard origin/master
    else
        echo "Clone LightGBM..."
        git -C "${third_party}" clone --recursive https://github.com/Microsoft/LightGBM.git lightgbm
    fi
    if [ -d "${third_party}/xgboost" ]; then
        git -C "${third_party}/xgboost" fetch -p
        git -C "${third_party}/xgboost" reset --hard origin/master
    else
        echo "Clone XGBoost..."
        git -C "${third_party}" clone --recursive https://github.com/dmlc/xgboost.git xgboost
    fi
fi

virtualenv=${build}/virtualenv/scikit-learn
if [ ${__build} ]; then
    virtualenv -p ${python} ${virtualenv}
fi
if [ -f ${virtualenv}/bin/activate ]; then
    source ${virtualenv}/bin/activate
fi
if [ ${__build} ]; then
    echo "Install scikit-learn"
    ${pip} install Cython
    ${pip} install numpy
    ${pip} install ${third_party}/scikit-learn
fi

if [ ${__update} ]; then
    echo "Update 'sklearn-metadata.json'"
    pushd ${tools}/metadata > /dev/null
    ${python} sklearn-metadata.py
    popd > /dev/null
fi

if [ -f ${virtualenv}/bin/activate ]; then
    deactivate
fi