#!/bin/bash

set -e

if [ $(which python3) ] && [ $(which pip3) ]; then
    export python=python3
    export pip=pip3
fi

root=$(cd $(dirname ${0})/../..; pwd)
tools=${root}/tools

echo "Update TensorFlow"
${tools}/metadata/tf-update

echo "Update Keras"
${tools}/metadata/keras-update

echo "Update CoreML"
${tools}/metadata/coreml-update

echo "Update Caffe"
${tools}/metadata/caffe-update

echo "Update MXNet"
${tools}/metadata/mxnet-update

echo "Update ONNX"
${tools}/metadata/onnx-update

echo "Update TensorFlow Lite"
${tools}/metadata/tflite-update

echo "Update PyTorch"
${tools}/metadata/pytorch-update
