#!/bin/bash

set -e

root=$(cd $(dirname ${0})/../..; pwd)
build=${root}/build
tools=${root}/tools
third_party=${root}/third_party

python=${python:-python}
pip=${pip:-pip}

identifier=coremltools
repository=https://github.com/apple/${identifier}.git

mkdir -p ${third_party}

if [ -d "${third_party}/${identifier}" ]; then
    git -C "${third_party}/${identifier}" fetch -p --quiet
    git -C "${third_party}/${identifier}" reset --quiet --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "${third_party}" clone --recursive ${repository}
fi

virtualenv=${build}/virtualenv/${identifier}
virtualenv -p ${python} ${virtualenv}
source ${virtualenv}/bin/activate

${pip} install --quiet onnx
${pip} install --quiet sklearn
${pip} install --quiet ${third_party}/${identifier}

${python} ${tools}/coreml-converter.py $@

deactivate