#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "armnn clean"
    rm -rf ./third_party/source/armnn
}

sync() {
    bold "armnn sync"
    [ -d "./third_party/source/armnn" ] || git clone --quiet --depth=1 --branch master https://github.com/ARM-software/armnn.git "./third_party/source/armnn"
    pushd "./third_party/source/armnn" > /dev/null
    git pull --quiet --prune
    popd > /dev/null
}

schema() {
    bold "armnn schema"
    [[ $(grep -U $'\x0D' ./source/armnn-schema.js) ]] && crlf=1
    node ./tools/flatc.js --text --root armnn --out ./source/armnn-schema.js ./third_party/source/armnn/src/armnnSerializer/ArmnnSchema.fbs
    if [[ -n ${crlf} ]]; then
        unix2dos --quiet --newfile ./source/armnn-schema.js ./source/armnn-schema.js
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
        "schema") schema;;
    esac
done
