#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

npm install
typescript=./node_modules/typescript/lib
uglifyjs=./node_modules/uglify-js/bin

rm -f -r ../Build

echo Building Debug
mkdir -p ../Build/Debug
cp ../Samples/index.html ../Build/Debug/index.html
node ${typescript}/tsc.js -target ES5 -out ../Build/Debug/netron.js ${typescript}/lib.d.ts ./libex.d.ts ../Source/*.ts

echo Building Release
mkdir -p ../Build/Release
cp ../Samples/index.html ../Build/Release/index.html
${uglifyjs}/uglifyjs ../Build/Debug/netron.js -o ../Build/Release/netron.js