#!/bin/bash

set -e

pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "caffe clean"
    rm -rf "./third_party/source/caffe"
}

sync() {
    bold "caffe sync"
    [ -d "./third_party/source/caffe" ] || git clone --quiet https://github.com/BVLC/caffe.git "./third_party/source/caffe"
    pushd "./third_party/source/caffe" > /dev/null
    git pull --quiet --prune
    popd > /dev/null
}

schema() {
    bold "caffe schema"
    [[ $(grep -U $'\x0D' ./source/caffe-proto.js) ]] && crlf=1
    temp=$(mktemp -d)
    sed 's/required float min = 1;/optional float min = 1;/g;s/required float max = 2;/optional float max = 2;/g' < ./third_party/source/caffe/src/caffe/proto/caffe.proto > ${temp}/caffe.proto
    node ./tools/protoc.js --text --root caffe --out ./source/caffe-proto.js ${temp}/caffe.proto
    rm -rf ${temp}
    if [[ -n ${crlf} ]]; then
        unix2dos --quiet --newfile ./source/caffe-proto.js ./source/caffe-proto.js
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
        "schema") schema;;
    esac
done
