#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "chainer clean"
    rm -rf "./third_party/src/chainer"
}

sync() {
    bold "chainer sync"
    [ -d "./third_party/src/chainer" ] || git clone --quiet https://github.com/chainer/chainer.git "./third_party/src/chainer"
    pushd "./third_party/src/chainer" > /dev/null
    git pull --quiet --prune
    popd > /dev/null
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
