#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "chainer clean"
    rm -rf "./third_party/src/chainer"
}

sync() {
    bold "chainer sync"
    mkdir -p "./third_party/src"
    if [ -d "./third_party/src/chainer" ]; then
        git -C "./third_party/src/chainer" pull --quiet --prune
    else
        git -C "./third_party/src" clone --quiet --recursive https://github.com/chainer/chainer.git
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
