#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "cntk clean"
    rm -rf "./third_party/cntk"
}

sync() {
    bold "cntk sync"
    mkdir -p "./third_party"
    if [ -d "./third_party/cntk" ]; then
        git -C "./third_party/cntk" pull --quiet --prune
    else
        git -C "./third_party" clone --quiet --recursive https://github.com/Microsoft/CNTK.git cntk
    fi
    git -C "./third_party/cntk" submodule sync --quiet
    git -C "./third_party/cntk" submodule update --quiet --init --recursive
}

schema() {
    bold "cntk schema"
    [[ $(grep -U $'\x0D' ./src/cntk-proto.js) ]] && crlf=1
    npx pbjs -t static-module -w closure --no-encode --no-delimited --no-comments --no-convert --no-verify --no-create --keep-case -r cntk -o ./src/cntk-proto.js ./third_party/cntk/Source/CNTKv2LibraryDll/proto/CNTK.proto
    node ./tools/update_pbjs.js array ./src/cntk-proto.js value float 1
    if [[ -n ${crlf} ]]; then
        unix2dos --quiet --newfile ./src/cntk-proto.js ./src/cntk-proto.js
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
        "schema") schema;;
    esac
done
