#!/bin/bash

set -e

tools=$(dirname ${0})
third_party=${tools}/../third_party

identifier=coremltools
repository=https://github.com/apple/${identifier}.git

mkdir -p ${third_party}

if [ -d "${third_party}/${identifier}" ]; then
    git -C "${third_party}/${identifier}" fetch -p
    git -C "${third_party}/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "${third_party}" clone --recursive ${repository}
fi

export PYTHONUSERBASE=${third_party}/${identifier}/build/pypi
export PATH=$PATH:${PYTHONUSERBASE}/bin
pip install --user onnx
pip install --user sklearn
pip install --user ${third_party}/${identifier}

python ${tools}/coreml-converter.py $@
