#!/bin/bash

set -e

mkdir -p ../third_party

identifier=coremltools
repository=https://github.com/apple/${identifier}.git

if [ -d "../third_party/${identifier}" ]; then
    git -C "../third_party/${identifier}" fetch -p
    git -C "../third_party/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "../third_party" clone --recursive ${repository}
fi

echo "Generate '../src/coreml.js'"
../node_modules/protobufjs/bin/pbjs -t static-module -w closure -r coreml -o ../src/coreml.js ../third_party/coremltools/mlmodel/format/Model.proto
