#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

git_sync() {
    mkdir -p "./third_party"
    if [ -d "./third_party/${1}" ]; then
        git -C "./third_party/${1}" pull --quiet --prune
    else
        git -C "./third_party" clone --quiet --recursive ${2} ${1}
    fi
}

clean() {
    bold "darknet clean"
    rm -rf ./third_party/darknet
}

sync() {
    bold "darknet sync"
    git_sync darknet https://github.com/AlexeyAB/darknet.git
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
