#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null
function exit_trap() {
    popd > /dev/null
}
trap exit_trap EXIT

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "deeplearning4j clean"
    rm -rf "./third_party/src/dl4j"
}

sync() {
    bold "deeplearning4j sync"
    mkdir -p "./third_party/src"
    if [ -d "./third_party/src/dl4j" ]; then
        git -C "./third_party/src/dl4j" pull --quiet --prune
    else
        git -C "./third_party/src" clone --quiet --recursive https://github.com/eclipse/deeplearning4j.git dl4j
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
