#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

# regenerate kann-schema.js with 'tools/kann schema'
schema() {
    echo "kann schema"
    [[ $(grep -U $'\x0D' ./source/kann-schema.js) ]] && crlf=1
    node ./tools/flatc.js --root kann --out ./source/kann-schema.js ./tools/kann.fbs
    if [[ -n ${crlf} ]]; then
        unix2dos --quiet --newfile ./source/kann-schema.js ./source/kann-schema.js
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "schema") schema;;
    esac
done
