#!/bin/bash

mkdir -p ../third_party

identifier=keras
repository=https://github.com/keras-team/${identifier}.git

if [ -d "../third_party/${identifier}" ]; then
    git -C "../third_party/${identifier}" fetch -p
    git -C "../third_party/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "../third_party" clone --recursive ${repository}
fi

echo "Update '../src/keras-metadata.json'"
python keras-metadata.py
