#!/bin/bash

mkdir -p ../third_party

identifier=keras
repository=https://github.com/keras-team/${identifier}.git

if [ -d "../third_party/${identifier}" ]; then
    pushd "../third_party/${identifier}" > /dev/null
    echo "Fetch ${repository}..."
    git fetch -p
    echo "Reset ${repository}..."
    git reset --hard origin/master
    popd > /dev/null
else
    echo "Clone ${repository}..."
    pushd "../third_party" > /dev/null
    git clone --recursive ${repository}
    popd > /dev/null
fi

echo "Update '../src/${identifier}-operator.json'"
python ${identifier}-operator-json.py
