#!/bin/bash

set -e

root=$(cd $(dirname ${0})/..; pwd)
tools=${root}/tools
third_party=${root}/third_party

identifier=keras
repository=https://github.com/keras-team/${identifier}.git

mkdir -p ${third_party}

if [ -d "${third_party}/${identifier}" ]; then
    git -C "${third_party}/${identifier}" fetch -p
    git -C "${third_party}/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "${third_party}" clone --recursive ${repository}
fi

echo "Update '../src/keras-metadata.json'"
pushd ${tools} > /dev/null
python keras-metadata.py
popd > /dev/null
