#!/bin/bash

set -e

mkdir -p ../third_party

identifier=incubator-mxnet
repository=https://github.com/apache/incubator-mxnet.git

if [ -d "../third_party/${identifier}" ]; then
    git -C "../third_party/${identifier}" fetch -p
    git -C "../third_party/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "../third_party" clone --recursive ${repository}
fi

# echo "Update '../src/mxnet-metadata.json'"
# python mxnet-metadata.py
