#!/bin/bash

set -e

root=$(cd $(dirname ${0})/..; pwd)
src=${root}/src
tools=${root}/tools
third_party=${root}/third_party

identifier=mxnet
repository=https://github.com/apache/incubator-${identifier}.git

mkdir -p ${third_party}

if [ -d "${third_party}/${identifier}" ]; then
    git -C "${third_party}/${identifier}" fetch -p
    git -C "${third_party}/${identifier}" reset --hard origin/master
else
    echo "Clone ${repository}..."
    git -C "${third_party}" clone --recursive ${repository} ${identifier}
fi

# echo "Update '../src/mxnet-metadata.json'"
# python mxnet-metadata.py
