#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "mxnet clean"
    rm -rf "./third_party/src/mxnet"
}

sync() {
    bold "mxnet sync"
    mkdir -p "./third_party/src"
    if [ -d "./third_party/src/mxnet" ]; then
        git -C "./third_party/src/mxnet" pull --quiet --prune
    else
        git -C "./third_party/src" clone --quiet --recursive https://github.com/apache/incubator-mxnet.git mxnet
    fi
    git -C "./third_party/src/mxnet" submodule sync --quiet
    git -C "./third_party/src/mxnet" submodule update --quiet --init --recursive
}

metadata() {
    bold "mxnet metadata"
    # python3 ./tools/mxnet-script.py
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
        "metadata") metadata;;
    esac
done
