#!/bin/bash

set -e

root=$(cd $(dirname ${0})/..; pwd)
src=${root}/src
third_party=${root}/third_party
tools=${root}/tools

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "mxnet clean"
    rm -rf "${third_party}/mxnet"
}

sync() {
    bold "mxnet sync"
    mkdir -p "${third_party}"
    if [ -d "${third_party}/mxnet" ]; then
        git -C "${third_party}/mxnet" pull --quiet --prune
    else
        git -C "${third_party}" clone --quiet --recursive https://github.com/apache/incubator-mxnet.git mxnet
    fi
    git -C "${third_party}/mxnet" submodule sync --quiet
    git -C "${third_party}/mxnet" submodule update --quiet --init --recursive
}

metadata() {
    bold "mxnet metadata"
    # python3 mxnet-script.py
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
        "metadata") metadata;;
    esac
done
