#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "ncnn clean"
    rm -rf "./third_party/ncnn"
}

sync() {
    bold "ncnn sync"
    mkdir -p "./third_party"
    if [ -d "./third_party/ncnn" ]; then
        git -C "./third_party/ncnn" pull --quiet --prune
    else
        git -C "./third_party" clone --quiet --recursive https://github.com/Tencent/ncnn.git ncnn
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
