#!/bin/bash

mkdir -p ../third_party

pushd "../third_party" > /dev/null
sudo rm -rf onnx
git clone --recursive git@github.com:onnx/onnx.git
popd > /dev/null

pushd "../third_party/onnx" > /dev/null
sudo python setup.py install
popd > /dev/null

echo "Generate '../src/onnx-ml.js'"
#../node_modules/protobufjs/bin/pbjs -w commonjs -t static-module -o ../src/onnx-ml.js ../third_party/onnx/onnx/onnx-ml.proto
../node_modules/protobufjs/bin/pbjs -t static-module -w closure -r onnx -o ../src/onnx-ml.js ../third_party/onnx/onnx/onnx-ml.proto

echo "Generate '../src/onnx-operator.json'"
python onnx-operator-json.py
