#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "paddle clean"
    rm -rf "./third_party/source/paddle"
}

sync() {
    bold "paddle sync"
    mkdir -p "./third_party/source/paddle/paddle/fluid/framework"
    curl --silent --location --output "./third_party/source/paddle/paddle/fluid/framework/framework.proto" "https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/framework.proto?raw=true"
}

schema() {
    bold "paddle schema"
    [[ $(grep -U $'\x0D' ./source/paddle-proto.js) ]] && crlf=1
    node ./tools/protoc.js --root paddle --out ./source/paddle-proto.js ./third_party/source/paddle/paddle/fluid/framework/framework.proto
    if [[ -n ${crlf} ]]; then
        unix2dos --quiet --newfile ./source/paddle-proto.js ./source/paddle-proto.js
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
        "schema") schema;;
    esac
done
