#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "tengine clean"
    rm -rf ./third_party/src/tengine
}

sync() {
    bold "tengine sync"
    [ -d "./third_party/src/tengine" ] || git clone --quiet --branch master https://github.com/OAID/Tengine.git "./third_party/src/tengine"
    pushd "./third_party/src/tengine" > /dev/null
    git pull --quiet --prune
    popd > /dev/null
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
