#!/bin/bash

set -e
pushd $(cd $(dirname ${0})/..; pwd) > /dev/null

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

clean() {
    bold "torch clean"
    rm -rf ./third_party/torch
}

sync() {
    bold "torch sync"
    mkdir -p "./third_party"
    if [ -d "./third_party/torch" ]; then
        git -C "./third_party/torch" pull --quiet --prune
    else
        git -C "./third_party" clone --quiet --recursive https://github.com/torch/torch7.git torch
    fi
}

while [ "$#" != 0 ]; do
    command="$1" && shift
    case "${command}" in
        "clean") clean;;
        "sync") sync;;
    esac
done
