#!/bin/bash

set -e

# export python=python3
# export pip=pip3

tools=$(dirname ${0})

${tools}/keras-update
${tools}/tf-update
${tools}/coreml-update
${tools}/caffe-update
${tools}/mxnet-update

${tools}/onnx-update
${tools}/tflite-update

${tools}/caffe2-update
