#!/usr/bin/python

import sys
import netron
import os

if __name__ == '__main__':
    args = sys.argv[1:]
    port = 8080
    browse = False
    initializer = False
    file = ''
    show_help = False
    while len(args) > 0:
        arg = args.pop(0)
        if (arg == '--help' or arg == '-h'):
            show_help = True
        elif (arg == '--port' or arg == '-p') and len(args) > 0 and args[0].isdigit(): 
            port = int(args.pop(0))
        elif arg == '--browse' or arg == '-b':
            browse = True
        elif arg == '--initialier' or arg == '-i':
            initialier = True
        elif not arg.startswith('-'):
            file = arg
    if show_help or len(file) == 0:
        print('')
        print('Usage: netron [--help]')
        print('              [--browse] [--port PORT] [--initializer] MODEL_FILE')
        print('')
        print('Options:')
        print('  -h, --help          Show this help message.')
        print('  -p, --port PORT     Port to serve (default: 8080).')
        print('  -b, --browse        Launch web browser.')
        print('  -i, --initializer   Keep graph initializer tensors.')
        print('')
        sys.exit(1)
    if not os.path.exists(file):
        print("Model file '" + file + "' does not exist.")
        sys.exit(2)
    netron.serve_file(file, browse=browse, port=port, initializer=initializer)
    sys.exit(0)
